### ISSUE TITLE
could you please provide a pretrained ckpt?

### ISSUE THREAD

**Issue by YiDai-03** [davidnvq/me_recognition#3]

**Comment by davidnvq** [comment]
I'm sorry that I haven't kept the datasets as well as the pre-trained models for quite a long time.
However, it took within a few hours to train the network using a single GPU. The results provided were the average of several trials. 
If the datasets are available to you, would you mind to train the models yourself? It would be nice to hear how well could you achieve after retraining those models.

Thanks.

**Comment by aliyatastemirova** [comment]
> I'm sorry that I haven't kept the datasets as well as the pre-trained models for quite a long time.
> However, it took within a few hours to train the network using a single GPU. The results provided were the average of several trials.
> If the datasets are available to you, would you mind to train the models yourself? It would be nice to hear how well could you achieve after retraining those models.
> 
> Thanks.

Hi, I am trying to run your code and I have the datasets. Just wanted to ask a few questions if you don't mind helping out. 
Is there a specific path/format for the datasets that the code expects? Is any preprocessing required?
I get an error that "fer_weight_path" is not defined in train_eval. I have not used pytorch before, so I am not sure if I missed something. I ran train_me_loso.py file like you wrote in readme.

Thanks in advance!

**Comment by davidnvq** [comment]
@aliyatastemirova: As I remember, because SMIC dataset doesn't provide the apex frames, you need to extract them by running `smic_preprocessing.py`. 
In fact, I provided the preprocessed annotations for such apex frames in the `datasets` folder. Please check those files inside this folder, and also the code for `Dataset` in [these files](https://github.com/davidnvq/me_recognition/blob/master/capsule/data).

It seems like I resumed the training so there was a line to load the weights from `fer_weight_path`. Feel free to remove/comment out this line. 

Thanks.

**Comment by aliyatastemirova** [comment]
> @aliyatastemirova: As I remember, because SMIC dataset doesn't provide the apex frames, you need to extract them by running `smic_preprocessing.py`.
> In fact, I provided the preprocessed annotations for such apex frames in the `datasets` folder. Please check those files inside this folder, and also the code for `Dataset` in [these files](https://github.com/davidnvq/me_recognition/blob/master/capsule/data).
> 
> It seems like I resumed the training so there was a line to load the weights from `fer_weight_path`. Feel free to remove/comment out this line.
> 
> Thanks.

Thank you very much for your response! I tried to run it again, but I noticed that nothing is passed to aux parameter in Dataset class? It stays None and breaks the code for me. I will try to figure out what should be passed there, but if you remember, I would appreciate your hints.

**Comment by davidnvq** [comment]
@aliyatastemirova Thank you for pointing it out. In fact, `aux` was used for debugging purpose. I already made a new commit to modify this error in line 42 and 43 of [this file](https://github.com/davidnvq/me_recognition/blob/master/capsule/data/dataset.py). 
May you take a look and give it a try again?

**Comment by davidnvq** [comment]
I'll close it, feel free to re-open it or open a new issue. Thanks!

**Comment by aliyatastemirova** [comment]
Hi, just wanted to update you, I have managed to run the files and train the model (took me a while as I don't have straightforward access to a GPU). I saved the model and scores files and added them into my forked repository. Feel free to copy it (I hope the result turned out how it is supposed to be) and add it to yours.

Thanks a lot for this code!

**Comment by davidnvq** [comment]
@aliyatastemirova Thank you a lot for such effort. You are more than welcome to create a PR from your forked repo as well.
